### PR TITLE
:sparkles: Adding keep alive

### PR DESCRIPTION
**Pull request by pugovok**
Adding keep alive

### CODE REVIEW

**Comment by bsr203** [comment]
@pavelnikolov can you please look at the pull req in this repo too. thanks

**Comment by pavelnikolov** [comment]
@bsr203 can you please add a unit test for this and I'd be happy to merge it.

**Comment by pavelnikolov** [comment]
I am not sure what the proper configuration on Heroku should be. Maybe you should ask their support team or read documentation....

**Comment by pavelnikolov** [comment]
@mattsrobot pull requests are welcome

**Pull request merged**
